
#
# Setup: run the following commands, to initialise config and ssl certificates.
# DOCKER_HOOKED_DIR=/tmp/hooked3
# docker run --rm -v ${DOCKER_HOOKED_DIR}:/hooked mountainpass/hooked --init --batch
# docker run --rm -v ${DOCKER_HOOKED_DIR}:/hooked mountainpass/hooked generate_ssl_certificates
#
# To show the version:
# docker run --rm mountainpass/hooked -v
#

services:
  hooked:
    image: mountainpass/hooked
    container_name: hooked
    environment:
      - DOCKER_HOOKED_DIR=/tmp/hooked
      - LOG_LEVEL=info
      - TZ=Australia/Sydney
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/hooked:/hooked
    command:
      - --server
      - --ssl
      # - --api-key=ABCD
    ports:
      - 4000:4000
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m