
#
# Setup: run the following commands, to initialise config and ssl certificates.
# DOCKER_HOOKED_DIR=/tmp/hooked
# docker run --rm -v ${DOCKER_HOOKED_DIR}:/hooked mountainpass/hooked --init --batch
# docker run --rm \
#   -e DOCKER_HOOKED_DIR=${DOCKER_HOOKED_DIR} \
#   -v /var/run/docker.sock:/var/run/docker.sock \
#   -v ${DOCKER_HOOKED_DIR}:/hooked \
#   mountainpass/hooked generate
#

services:
  hooked:
    image: mountainpass/hooked
    environment:
      - DOCKER_HOOKED_DIR=/tmp/hooked
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/hooked:/hooked
    command:
      - --server
      - --ssl
      - --api-key=ABCD
    ports:
      - 4000:4000